doctrine:
    orm:
        dql:
            datetime_functions:
                DATE: DoctrineExtensions\Query\Mysql\Date
                YEAR: DoctrineExtensions\Query\Mysql\Year
                MONTH: DoctrineExtensions\Query\Mysql\Month
                DAY: DoctrineExtensions\Query\Mysql\Day
                DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat
                DATE_ADD: DoctrineExtensions\Query\Mysql\DateAdd
                DATE_SUB: DoctrineExtensions\Query\Mysql\DateSub
                DATEDIFF: DoctrineExtensions\Query\Mysql\DateDiff
                NOW: DoctrineExtensions\Query\Mysql\Now
            string_functions:
                CONCAT: DoctrineExtensions\Query\Mysql\Concat
                CONCAT_WS: DoctrineExtensions\Query\Mysql\ConcatWs
                SUBSTRING: DoctrineExtensions\Query\Mysql\Substring
                REPLACE: DoctrineExtensions\Query\Mysql\Replace
            numeric_functions:
                ROUND: DoctrineExtensions\Query\Mysql\Round
                RAND: DoctrineExtensions\Query\Mysql\Rand
