parameters:
    app.fcm_access_token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJmaXJlYmFzZS1hZG1pbnNkay1mYnN2Y0Bzb2xkZXRyYWNrLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwic2NvcGUiOiJodHRwczpcL1wvd3d3Lmdvb2dsZWFwaXMuY29tXC9hdXRoXC9maXJlYmFzZS5tZXNzYWdpbmciLCJhdWQiOiJodHRwczpcL1wvb2F1dGgyLmdvb2dsZWFwaXMuY29tXC90b2tlbiIsImV4cCI6MTc1ODA0ODI5MCwiaWF0IjoxNzU4MDQ0NjkwfQ.OU6g3wG7rnMOPRXIZwLhv1LV2bNOgpwulXEL_we7I7QL8d4dKTMcj7lK15XEepIqMkI-sYuvU29IuXqg4r9wM9dAjex75WO7GBKj1RhPIga9n2kEN1CLgrmalyISfwhWxZvoOmwPFkWv-dqfLVkbabCdbXZo5X3UY6VPaUwnG251j8uV6RAW81bFANFJ0BAqxf6cafISJWyAIfiOpkpIQOV1nLw0x4G2fOgzXdr5Slaj0Ssd7qrwgfuB0Wx50RqgWwBlY31M7OJiPmHOnnX9Ei-fzjIaPaaJSjIKuKduEwxe03U_Rk6ryxCaOoAnkkemlfH47lvXlRRQaTOP9_A_pA'
    app.fcm_project_id: 'soldetrack'

services:
    App\Service\NotificationService:
        arguments:
            $params: '@parameter_bag'
            $logger: '@logger'
